#pragma once

#include "stdint.h"
#include "sensor.h"
typedef enum
{
    // MSG FROM NEXTION RX TO MAIN TASK
    MIN_LOADED,
    HOME_LOADED,
    SYSTEM_SETTINGS_LOADED,
    CALIBRATION_LOADED,
    INPUTCALIBP1_LOADED,
    INPUTCALIBP2_LOADED,
    INPUTCALIBP3_LOADED,
    INPUTCALIBP4_LOADED,
    KEYBDA_LOADED,
    NUMPAD_POPUP_LOADED,
    INTRO_LOADED,
    INPUTCONFIGP1_LOADED,
    NEW_TEST_P1_LOADED,
    NEW_TEST_P2_LOADED,
    NEW_TEST_P3_1_LOADED,
    NEW_TEST_P3_2_LOADED,
    NEW_TEST_P3_3_LOADED,
    NEW_TEST_P3_4_LOADED,
    LOG_SENSOR_TABLE_LOADED,
    LOG_TIME_TABLE_LOADED,
    NEW_TEST_P4_1_LOADED,
    NEW_TEST_P4_2_LOADED,
    NEW_TEST_P4_3_LOADED,
    NEW_TEST_P4_4_LOADED,
    NEW_TEST_P4_5_LOADED,
    NEW_TEST_P4_6_LOADED,
    NEW_TEST_P4_7_LOADED,
    NEW_TEST_P4_8_LOADED,
    NEW_TEST_P4_9_LOADED,
    NEW_TEST_P5_LOADED,
    NEW_TEST_P6_LOADED,
    NEW_TEST_P7_1_LOADED,
    NEW_TEST_P7_2_LOADED,
    NEW_TEST_P7_3_LOADED,
    NEW_TEST_P7_4_LOADED,
    PREVIOUS_TEST_P1_LOADED,
    PREVIOUS_TEST_P2_LOADED,
    PREVIOUS_TEST_P3_LOADED,
    EXPORT_TEST_LOADED,
    DELETE_TEST_LOADED,
    MESSAGE_LOADED,
    CURRENT_TEST_P1_LOADED,
    CURRENT_TEST_P2_LOADED,
    CURRENT_TEST_P3_LOADED,
    MAX_LOADED,

    // HOME
    TARA_ENABLED,
    TARA_DISABLED,
    GOTO_NEW_TEST_FROM_HOME,
    GOTO_CURRENT_TEST_FROM_HOME,

    // CALIBRATION
    SENSOR_DISABLED,
    SENSOR_ENABLED,
    LIMITS_DISABLED,
    LIMITS_ENABLED,

    // DATETIME
    DATETIME_RTC_ALL_AT_ONCE_RECEIVED,

    // INPUT CALIBRATION
    INPUT_CALIBRATION_MIN,
    INPUTCALIBP1_TYPE_RECEIVED,
    INPUTCALIBP1_CAPACITY_RECEIVED,
    INPUTCALIBP1_CAPACITY_UNIT_RECEIVED,
    INPUTCALIBP1_SENSIBILITY_RECEIVED,
    INPUTCALIBP1_SENSIBILITY_UNIT_RECEIVED,
    INPUTCALIBP1_SENSOR_INDEX_RECEIVED,

    INPUTCALIBP2_CALIBRATION_LIMIT_RECEIVED,
    INPUTCALIBP2_CALIBRATION_LIMIT_UNIT_RECEIVED,
    INPUTCALIBP2_LIMIT_ENABLE_RECEIVED,

    INPUTCALIBP3_TABLE_RECEIVED,
    INPUTCALIBP3_NUM_POINTS_RECEIVED,
    INPUTCALIBP3_ROW_TO_FILL_RECEIVED,

    INPUTCALIBP4_NAME_RECEIVED,
    INPUTCALIBP4_SAVE_PRESSED,

    INPUTCONFIGP1_TYPE_RECEIVED,
    INPUTCONFIGP1_CAPACITY_RECEIVED,
    INPUTCONFIGP1_CAPACITY_UNIT_RECEIVED,
    INPUTCONFIGP1_NAME_RECEIVED,
    INPUTCONFIGP1_INDEX_RECEIVED,
    INPUTCONFIGP1_SAVE_PRESSED,
    INPUT_CALIBRATION_MAX,

    // NEW TEST
    NEW_TEST_MIN,
    NEW_TEST_P1_TYPE_RECEIVED,
    NEW_TEST_P2_INPUTS_RECEIVED,
    NEW_TEST_P3_1_LOGGING_RECEIVED,
    NEW_TEST_P3_2_LOGGING_RECEIVED,
    NEW_TEST_P3_3_LOGGING_RECEIVED,
    NEW_TEST_P3_4_LOGGING_RECEIVED,
    NEW_TEST_P4_1_STOP_RECEIVED,
    NEW_TEST_P4_2_STOP_RECEIVED,
    NEW_TEST_P4_3_STOP_RECEIVED,
    NEW_TEST_P4_4_STOP_RECEIVED,
    NEW_TEST_P4_5_STOP_RECEIVED,
    NEW_TEST_P4_6_STOP_RECEIVED,
    NEW_TEST_P4_7_STOP_RECEIVED,
    NEW_TEST_P4_8_STOP_RECEIVED,
    NEW_TEST_P4_9_STOP_RECEIVED,
    NEW_TEST_P6_GRAPH_RECEIVED,
    NEW_TEST_P7_1_START_RECEIVED,
    NEW_TEST_P7_2_START_RECEIVED,
    NEW_TEST_P7_3_START_RECEIVED,
    NEW_TEST_P7_3_TRIGGER_INPUT_RECEIVED,
    NEW_TEST_P7_4_START_RECEIVED,
    NEW_TEST_P7_4_TRIGGER_INPUT_RECEIVED,
    NEW_TEST_MAX,

    // CURRENT TEST
    CURRENT_TEST_OPERATOR_STOP,

    // MAIN TIMER
    PERIODIC_100MS,
    PERIODIC_300MS,
    PERIODIC_1S,
    PERIODIC_1MIN,
    PERIODIC_10MIN,

    //

    NEXTION_UPDATE,

    //
    SENSOR_UNIT_CHANGED,
    SENSOR_READING_RECEIVED,
    SENSOR_CLASS_RECEIVED,

    // TIME
    TIME_RTC_START_SYNC,
    TIME_RTC_DATA_RECEIVED,
    TIME_DATETIME_PRINT,

    // USB
    USB_CONNECTED,
    USB_DISCONNECTED,

} msg_type_t;

typedef enum
{
    PAGE_HOME = 0,
    PAGE_SYSTEM_SETTINGS = 1,
    PAGE_CALIBRATION = 2,
    PAGE_PSWD_POPUP = 3,
    PAGE_DATETIME = 4,
    PAGE_DISPLAY = 5,
    PAGE_SETCALIB_POPUP = 6,
    PAGE_SELECT_POPUP = 7,
    PAGE_INPUTCALIBP1 = 8,
    PAGE_INPUTCALIBP2 = 9,
    PAGE_INPUTCALIBP3 = 10,
    PAGE_INPUTCALIBP4 = 11,
    PAGE_KEYBDA = 12,
    PAGE_NUMPAD_POPUP = 13,
    PAGE_INTRO = 14,
    PAGE_INPUTCONFIGP1 = 15,
    PAGE_NEW_TEST_P1 = 16,
    PAGE_NEW_TEST_P2 = 17,
    PAGE_NEW_TEST_P3_1 = 18,
    PAGE_NEW_TEST_P3_2 = 19,
    PAGE_NEW_TEST_P3_3 = 20,
    PAGE_NEW_TEST_P3_4 = 21,
    PAGE_LOG_SENSOR_TABLE = 22,
    PAGE_LOG_TIME_TABLE = 23,
    PAGE_NEW_TEST_P4_1 = 24,
    PAGE_NEW_TEST_P4_2 = 25,
    PAGE_NEW_TEST_P4_3 = 26,
    PAGE_NEW_TEST_P4_4 = 27,
    PAGE_NEW_TEST_P4_5 = 28,
    PAGE_NEW_TEST_P4_6 = 29,
    PAGE_NEW_TEST_P4_7 = 30,
    PAGE_NEW_TEST_P4_8 = 31,
    PAGE_NEW_TEST_P4_9 = 32,
    PAGE_NEW_TEST_P5 = 33,
    PAGE_NEW_TEST_P6 = 34,
    PAGE_NEW_TEST_P7_1 = 35,
    PAGE_NEW_TEST_P7_2 = 36,
    PAGE_NEW_TEST_P7_3 = 37,
    PAGE_NEW_TEST_P7_4 = 38,
    PAGE_PREVIOUS_TEST_P1 = 39,
    PAGE_PREVIOUS_TEST_P2 = 40,
    PAGE_PREVIOUS_TEST_P3 = 41,
    PAGE_EXPORT_TEST = 42,
    PAGE_DELETE_TEST = 43,
    PAGE_MESSAGE = 44,
    PAGE_CURRENT_TEST_P1 = 45,
    PAGE_CURRENT_TEST_P2 = 46,
    PAGE_CURRENT_TEST_P3 = 47,
} page_t;

typedef struct
{
    msg_type_t type;
    union
    {
        uint32_t u32;
        float f32;
        int32_t i32;
        void *addr;
        content_reading_t cr;
        content_class_t cc;
        content_str_t cs;
    } content;
    int size;
} msg_t;
